RAW_COPPER = 12.0
STONE_BRICKS = 2.0
REDSTONE = 4.0
NETHER_QUARTZ_ORE = 40.0
SANDSTONE = 4.0
CRIMSON_STEM = 10.0
COAL = 8.0
RAW_GOLD_BLOCK = 270.0
NETHER_BRICK = 2.0
MANGROVE_PLANKS = 6.0
ACACIA_LOG = 8.0
SPRUCE_PLANKS = 2.0
GOLD_BLOCK = 360.0
CRIMSON_PLANKS = 6.0
REDSTONE_BLOCK = 36.0
DEEPSLATE_LAPIS_ORE = 120.0
BRICKS = 15.0
COBBLESTONE_SLAB = 1.0
COPPER_INGOT = 17.0
QUARTZ = 10.0
LAPIS_LAZULI = 8.0
QUARTZ_BLOCK = 40.0
SAND = 1.0
RAW_IRON_BLOCK = 75.0
DIRT = 1.0
NETHERITE_INGOT = 260.0
MOSSY_COBBLESTONE = 5.0
JUNGLE_LOG = 8.0
CUT_SANDSTONE = 4.0
WARPED_PLANKS = 6.0
IRON_INGOT = 15.0
SPRUCE_LOG = 8.0
LAPIS_BLOCK = 70.0
DEEPSLATE_DIAMOND_ORE = 140.0
WHITE_WOOL = 6.0
DARK_OAK_PLANKS = 2.0
COBBLESTONE_STAIRS = 2.0
JUNGLE_PLANKS = 2.0
DIAMOND_BLOCK = 1450.0
WARPED_STEM = 10.0
OBSIDIAN = 12.0
DIAMOND = 160.0
COBBLESTONE = 1.0
REDSTONE_ORE = 60.0
GLOWSTONE_DUST = 4.0
GOLD_INGOT = 40.0
END_STONE = 20.0
GRAVEL = 3.0
CHARCOAL = 8.0
RAW_GOLD = 30.0
OAK_PLANKS = 2.0
NETHERITE_SCRAP = 280.0
SMOOTH_STONE_SLAB = 1.0
IRON_BLOCK = 135.0
LAPIS_ORE = 120.0
GLOWSTONE = 15.0
GRASS_BLOCK = 4.0
EMERALD_ORE = 800.0
OAK_LOG = 8.0
COAL_ORE = 30.0
DEEPSLATE_COAL_ORE = 30.0
SNOWBALL = 2.0
NETHER_BRICKS = 8.0
EMERALD_BLOCK = 400.0
SOUL_SAND = 4.0
EMERALD = 100.0
BIRCH_LOG = 8.0
BIRCH_PLANKS = 2.0
ICE = 6.0
MYCELIUM = 10.0
ACACIA_PLANKS = 2.0
DIAMOND_ORE = 240.0
DEEPSLATE_REDSTONE_ORE = 60.0
CLAY_BALL = 3.0
BLUE_ICE = 10.0
DEEPSLATE_EMERALD_ORE = 200.0
IRON_ORE = 12.0
NETHERRACK = 1.0
STONE_SLAB = 1.0
DEEPSLATE_IRON_ORE = 12.0
RAW_IRON = 12.0
SNOW_BLOCK = 4.0
AMETHYST_SHARD = 100.0
GOLD_ORE = 30.0
COAL_BLOCK = 72.0
PACKED_ICE = 8.0
SOUL_SOIL = 4.0
STONE = 2.0
DARK_OAK_LOG = 8.0
CLAY = 12.0
DEEPSLATE_GOLD_ORE = 30.0